
version: '3'
services:


  mongodb:
    image: mongo:6
    container_name: mongo_search_mongodbb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  atlas-api:
    image: node:18
    container_name: mongo_search_atlas_apii
    volumes:
      - ./atlas-searchapi.ts:/atlas-searchapi.ts
      - ./util.ts:/util.ts
      - ./node_modules:/node_modules
      - ./tsconfig.json:/tsconfig.json
      - ./package.json:/package.json
    ports:
      - 3001:3001
    command: npx ts-node atlas-api.ts
    env_file: .env.atlas
    depends_on:
      - mongodb
